import type { BookOptionDef } from "./types";

/** Registre unique : id stable → métadonnées + clé Typst. */
export const BOOK_OPTIONS: BookOptionDef[] = [
  {
    id: "chapter-title-in-header",
    kind: "bool",
    typstKey: "chapter-title-in-header",
    labelKey: "chapterTitleInHeader",
  },
  {
    id: "page-number-placement",
    kind: "enum",
    typstKey: "page-number-placement",
    enumValues: ["spread", "center", "outer"],
    labelKey: "pageNumberPlacement",
    enumValueKeys: true,
  },
  {
    id: "header-footer-rule",
    kind: "enum",
    typstKey: "header-footer-rule",
    enumValues: ["none", "thin", "thick"],
    labelKey: "headerFooterRule",
    enumValueKeys: true,
  },
  {
    id: "page-number-style",
    kind: "enum",
    typstKey: "page-number-style",
    enumValues: ["arabic", "roman", "page-n-of-m"],
    labelKey: "pageNumberStyle",
    enumValueKeys: true,
  },
  {
    id: "auto-heading-numbering",
    kind: "bool",
    typstKey: "auto-heading-numbering",
    labelKey: "autoHeadingNumbering",
  },
  {
    id: "h1-typography",
    kind: "enum",
    typstKey: "h1-typography",
    enumValues: ["uppercase", "normal", "centered", "left"],
    labelKey: "h1Typography",
    enumValueKeys: true,
  },
  {
    id: "drop-cap-first-para",
    kind: "bool",
    typstKey: "drop-cap-first-para",
    labelKey: "dropCapFirstPara",
  },
  {
    id: "line-spacing-preset",
    kind: "enum",
    typstKey: "line-spacing-preset",
    enumValues: ["standard", "narrow", "wide"],
    labelKey: "lineSpacingPreset",
    enumValueKeys: true,
  },
  {
    id: "chapter-start-odd",
    kind: "bool",
    typstKey: "chapter-start-odd",
    labelKey: "chapterStartOdd",
  },
  {
    id: "binding-gutter-mm",
    kind: "enum",
    typstKey: "binding-gutter-mm",
    enumValues: ["0", "5", "10"],
    labelKey: "bindingGutterMm",
    enumValueKeys: true,
  },
  {
    id: "transition-blank-style",
    kind: "enum",
    typstKey: "transition-blank-style",
    enumValues: ["empty", "with-running-headers"],
    labelKey: "transitionBlankStyle",
    enumValueKeys: true,
  },
  {
    id: "caption-position",
    kind: "enum",
    typstKey: "caption-position",
    enumValues: ["above", "below"],
    labelKey: "captionPosition",
    enumValueKeys: true,
  },
  {
    id: "footnote-scope",
    kind: "enum",
    typstKey: "footnote-scope",
    enumValues: ["document", "chapter"],
    labelKey: "footnoteScope",
    enumValueKeys: true,
  },
  {
    id: "image-treatment",
    kind: "enum",
    typstKey: "image-treatment",
    enumValues: ["full-width", "float", "auto-margins"],
    labelKey: "imageTreatment",
    enumValueKeys: true,
  },
  {
    id: "accent-color",
    kind: "color",
    typstKey: "accent-color",
    labelKey: "accentColor",
  },
  {
    id: "show-index",
    kind: "bool",
    typstKey: "show-index",
    labelKey: "showIndex",
  },
  {
    id: "list-figures-style",
    kind: "enum",
    typstKey: "list-figures-style",
    enumValues: ["none", "after-toc", "end"],
    labelKey: "listFiguresStyle",
    enumValueKeys: true,
  },
  {
    id: "show-glossary",
    kind: "bool",
    typstKey: "show-glossary",
    labelKey: "showGlossary",
  },
  {
    id: "cover-page",
    kind: "bool",
    typstKey: "cover-page",
    labelKey: "coverPage",
  },
  {
    id: "half-title-page",
    kind: "bool",
    typstKey: "half-title-page",
    labelKey: "halfTitlePage",
  },
  {
    id: "title-page",
    kind: "bool",
    typstKey: "title-page",
    labelKey: "titlePage",
  },
  {
    id: "front-title-recto-with-blank-before",
    kind: "bool",
    typstKey: "front-title-recto-with-blank-before",
    labelKey: "frontTitleRectoBlankBefore",
  },
  {
    id: "section-new-page",
    kind: "bool",
    typstKey: "section-new-page",
    labelKey: "sectionNewPage",
  },
  {
    id: "section-title-recto-with-blank-before",
    kind: "bool",
    typstKey: "section-title-recto-with-blank-before",
    labelKey: "sectionTitleRectoBlankBefore",
  },
  {
    id: "toc-position",
    kind: "enum",
    typstKey: "toc-position",
    enumValues: ["none", "start", "end"],
    labelKey: "tocPosition",
    enumValueKeys: true,
  },
  {
    id: "toc-depth",
    kind: "enum",
    typstKey: "toc-depth",
    enumValues: ["1", "2", "3"],
    labelKey: "tocDepth",
    enumValueKeys: true,
  },
  {
    id: "bibliography-position",
    kind: "enum",
    typstKey: "bibliography-position",
    enumValues: ["none", "start", "end"],
    labelKey: "bibliographyPosition",
    enumValueKeys: true,
  },
  {
    id: "widows-orphans",
    kind: "enum",
    typstKey: "widows-orphans",
    enumValues: ["on", "off"],
    labelKey: "widowsOrphans",
    enumValueKeys: true,
  },
  {
    id: "show-annexes",
    kind: "bool",
    typstKey: "show-annexes",
    labelKey: "showAnnexes",
  },
  {
    id: "show-back-cover",
    kind: "bool",
    typstKey: "show-back-cover",
    labelKey: "showBackCover",
  },
];

/** Clés de surcharge pour titres (optionnel, sinon chaîne selon documentLang). */
export const STRING_OVERRIDE_KEYS = [
  "label-toc",
  "label-bibliography",
  "label-index",
  "label-glossary",
  "label-list-figures",
  "label-annexes",
] as const;

export type StringOverrideKey = (typeof STRING_OVERRIDE_KEYS)[number];

export const BOOK_OPTION_BY_ID: Record<string, BookOptionDef> = Object.fromEntries(
  BOOK_OPTIONS.map((o) => [o.id, o]),
);
