// Catalogue des clés `conf` fusionnées par les gabarits ObbWasm (valeurs neutres).
// Les gabarits font `#import ".../book-options-defaults.typ": book-options-defaults` puis `..book-options-defaults`.

#let book-options-defaults = (
  chapter-title-in-header: true,
  page-number-placement: "outer",
  header-footer-rule: "none",
  page-number-style: "arabic",
  page-numbering-pattern: "1",
  heading-numbering: "none",
  auto-heading-numbering: false,
  h1-typography: "centered",
  drop-cap-first-para: false,
  line-spacing-preset: "standard",
  body-text-alignment: "justify",
  chapter-start-odd: false,
  binding-gutter: 0mm,
  transition-blank-style: "empty",
  caption-position: "below",
  footnote-scope: "document",
  image-treatment: "auto-margins",
  accent-color: "#333333",
  show-index: false,
  list-figures-style: "none",
  show-glossary: false,
  widows-orphans: "on",
  show-annexes: false,
  show-back-cover: false,
  toc-position: "none",
  toc-depth: "3",
  toc-at-start: false,
  toc-at-end: false,
  bibliography-position: "none",
  bibliography-at-start: false,
  bibliography-at-end: false,
  document-lang: "fr",
  section-order: ("body",),
  label-toc: "",
  label-bibliography: "",
  label-index: "",
  label-glossary: "",
  label-list-figures: "",
  label-annexes: "",
)
